export const entrepreneurshipLists = {
      entrepreneurship: {
        name: 'Emprendimiento',
        words: [
            { word: 'Acción', translation: 'Stock' },
            { word: 'Accionista', translation: 'Shareholder' },
            { word: 'Activos', translation: 'Assets' },
            { word: 'Administración', translation: 'Management' },
            { word: 'Amortización', translation: 'Amortization' },
            { word: 'Análisis técnico', translation: 'Technical analysis' },
            { word: 'Análisis fundamental', translation: 'Fundamental analysis' },
            { word: 'Apalancamiento', translation: 'Leverage' },
            { word: 'Apreciación', translation: 'Appreciation' },
            { word: 'Arancel', translation: 'Tariff' },
            { word: 'Asesor financiero', translation: 'Financial advisor' },
            { word: 'Auditoría', translation: 'Audit' },
            { word: 'Balance', translation: 'Balance sheet' },
            { word: 'Banco', translation: 'Bank' },
            { word: 'Banco central', translation: 'Central bank' },
            { word: 'Beneficio', translation: 'Profit' },
            { word: 'Bienes', translation: 'Goods' },
            { word: 'Bolsa', translation: 'Stock market' },
            { word: 'Bonos', translation: 'Bonds' },
            { word: 'Bróker', translation: 'Broker' },
            { word: 'Capital', translation: 'Capital' },
            { word: 'Capital de riesgo', translation: 'Venture capital' },
            { word: 'Capitalización', translation: 'Capitalization' },
            { word: 'Cartera', translation: 'Portfolio' },
            { word: 'Cliente', translation: 'Client' },
            { word: 'Cobertura', translation: 'Hedge' },
            { word: 'Comercio', translation: 'Trade' },
            { word: 'Comisión', translation: 'Commission' },
            { word: 'Competencia', translation: 'Competition' },
            { word: 'Comprador', translation: 'Buyer' },
            { word: 'Compra', translation: 'Purchase' },
            { word: 'Consolidación', translation: 'Consolidation' },
            { word: 'Consumo', translation: 'Consumption' },
            { word: 'Contabilidad', translation: 'Accounting' },
            { word: 'Contrato', translation: 'Contract' },
            { word: 'Cotización', translation: 'Quotation' },
            { word: 'Crédito', translation: 'Credit' },
            { word: 'Crecimiento', translation: 'Growth' },
            { word: 'Cuota de mercado', translation: 'Market share' },
            { word: 'Dato económico', translation: 'Economic data' },
            { word: 'Déficit', translation: 'Deficit' },
            { word: 'Demanda', translation: 'Demand' },
            { word: 'Depósito', translation: 'Deposit' },
            { word: 'Derivado', translation: 'Derivative' },
            { word: 'Desempleo', translation: 'Unemployment' },
            { word: 'Desinversión', translation: 'Divestment' },
            { word: 'Deuda', translation: 'Debt' },
            { word: 'Dividendo', translation: 'Dividend' },
            { word: 'Dólar', translation: 'Dollar' },
            { word: 'Economía', translation: 'Economy' },
            { word: 'Eficiencia', translation: 'Efficiency' },
            { word: 'Empresa', translation: 'Company' },
            { word: 'Emprendedor', translation: 'Entrepreneur' },
            { word: 'Emprendimiento', translation: 'Entrepreneurship' },
            { word: 'Emisión', translation: 'Issuance' },
            { word: 'Entrada', translation: 'Entry' },
            { word: 'Entrevista', translation: 'Interview' },
            { word: 'Escalabilidad', translation: 'Scalability' },
            { word: 'Escasez', translation: 'Shortage' },
            { word: 'Estado financiero', translation: 'Financial statement' },
            { word: 'Estrategia', translation: 'Strategy' },
            { word: 'Evaluación', translation: 'Evaluation' },
            { word: 'Excedente', translation: 'Surplus' },
            { word: 'Exportación', translation: 'Export' },
            { word: 'Factibilidad', translation: 'Feasibility' },
            { word: 'Factura', translation: 'Invoice' },
            { word: 'Financiación', translation: 'Funding' },
            { word: 'Financiamiento', translation: 'Financing' },
            { word: 'Flujo de caja', translation: 'Cash flow' },
            { word: 'Fondos', translation: 'Funds' },
            { word: 'Fondo de inversión', translation: 'Investment fund' },
            { word: 'Fondos mutuos', translation: 'Mutual funds' },
            { word: 'Fondo de pensiones', translation: 'Pension fund' },
            { word: 'Ganancia', translation: 'Gain' },
            { word: 'Gastos', translation: 'Expenses' },
            { word: 'Garantía', translation: 'Guarantee' },
            { word: 'Globalización', translation: 'Globalization' },
            { word: 'Hacienda', translation: 'Treasury' },
            { word: 'Hipoteca', translation: 'Mortgage' },
            { word: 'Impuesto', translation: 'Tax' },
            { word: 'Importación', translation: 'Import' },
            { word: 'Índice bursátil', translation: 'Stock index' },
            { word: 'Industria', translation: 'Industry' },
            { word: 'Inflación', translation: 'Inflation' },
            { word: 'Ingreso', translation: 'Income' },
            { word: 'Innovación', translation: 'Innovation' },
            { word: 'Inseguridad', translation: 'Uncertainty' },
            { word: 'Inversión', translation: 'Investment' },
            { word: 'Inversionista', translation: 'Investor' },
            { word: 'IVA', translation: 'VAT' },
            { word: 'Jurídico', translation: 'Legal' },
            { word: 'Largo plazo', translation: 'Long term' },
            { word: 'Legalidad', translation: 'Legality' },
            { word: 'Liquidez', translation: 'Liquidity' },
            { word: 'Logística', translation: 'Logistics' },
            { word: 'Margen', translation: 'Margin' },
            { word: 'Marketing', translation: 'Marketing' },
            { word: 'Materias primas', translation: 'Raw materials' },
            { word: 'Mercado', translation: 'Market' },
            { word: 'Meta', translation: 'Goal' },
            { word: 'Microempresa', translation: 'Microenterprise' },
            { word: 'Microeconomía', translation: 'Microeconomics' },
            { word: 'Millón', translation: 'Million' },
            { word: 'Modelo de negocio', translation: 'Business model' },
            { word: 'Moneda', translation: 'Currency' },
            { word: 'Monopolio', translation: 'Monopoly' },
            { word: 'Multinacional', translation: 'Multinational' },
            { word: 'Negociación', translation: 'Negotiation' },
            { word: 'Nivel de riesgo', translation: 'Risk level' },
            { word: 'Nómina', translation: 'Payroll' },
            { word: 'Oferta', translation: 'Supply' },
            { word: 'Operación', translation: 'Operation' },
            { word: 'Oportunidad', translation: 'Opportunity' },
            { word: 'Organización', translation: 'Organization' },
            { word: 'Pagaré', translation: 'Promissory note' },
            { word: 'Pasivo', translation: 'Liability' },
            { word: 'Patente', translation: 'Patent' },
            { word: 'Patrimonio', translation: 'Equity' },
            { word: 'Pago', translation: 'Payment' },
            { word: 'Pérdida', translation: 'Loss' },
            { word: 'Pensión', translation: 'Pension' },
            { word: 'Periodo fiscal', translation: 'Fiscal period' },
            { word: 'PIB', translation: 'GDP' },
            { word: 'Plan de negocios', translation: 'Business plan' },
            { word: 'Plazo', translation: 'Term' },
            { word: 'Precio', translation: 'Price' },
            { word: 'Precio objetivo', translation: 'Target price' },
            { word: 'Prestamista', translation: 'Lender' },
            { word: 'Presupuesto', translation: 'Budget' },
            { word: 'Prima', translation: 'Premium' },
            { word: 'Producto mínimo viable', translation: 'Minimum viable product' },
            { word: 'Productividad', translation: 'Productivity' },
            { word: 'Producto', translation: 'Product' },
            { word: 'Proveedor', translation: 'Supplier' },
            { word: 'Préstamo', translation: 'Loan' },
            { word: 'Publicidad', translation: 'Advertising' },
            { word: 'Punto de equilibrio', translation: 'Break-even point' },
            { word: 'Quiebra', translation: 'Bankruptcy' },
            { word: 'Recesión', translation: 'Recession' },
            { word: 'Reforma', translation: 'Reform' },
            { word: 'Rentabilidad', translation: 'Profitability' },
            { word: 'Reporte', translation: 'Report' },
            { word: 'Recursos', translation: 'Resources' },
            { word: 'Regulación', translation: 'Regulation' },
            { word: 'Riesgo', translation: 'Risk' },
            { word: 'Riqueza', translation: 'Wealth' },
            { word: 'ROI', translation: 'Return on Investment' },
            { word: 'Salario', translation: 'Salary' },
            { word: 'Sede', translation: 'Headquarters' },
            { word: 'Volatilidad', translation: 'Volatility' },
        ],
      }
    };