export const levelLists = {
      basic: {
        name: 'Básico (A1-A2)',
        words: [
            { word: 'Hola', translation: 'Hello' },
            { word: 'Adiós', translation: 'Goodbye' },
            { word: 'Por favor', translation: 'Please' },
            { word: 'Gracias', translation: 'Thank you' },
            { word: 'De nada', translation: 'You\'re welcome' },
            { word: 'Sí', translation: 'Yes' },
            { word: 'No', translation: 'No' },
            { word: 'Hombre', translation: 'Man' },
            { word: 'Mujer', translation: 'Woman' },
            { word: 'Niño', translation: 'Boy' },
            { word: 'Niña', translation: 'Girl' },
            { word: 'Amigo', translation: 'Friend' },
            { word: 'Casa', translation: 'House' },
            { word: 'Escuela', translation: 'School' },
            { word: 'Libro', translation: 'Book' },
            { word: 'Mesa', translation: 'Table' },
            { word: 'Silla', translation: 'Chair' },
            { word: 'Agua', translation: 'Water' },
            { word: 'Comida', translation: 'Food' },
            { word: 'Pan', translation: 'Bread' },
            { word: 'Leche', translation: 'Milk' },
            { word: 'Café', translation: 'Coffee' },
            { word: 'Té', translation: 'Tea' },
            { word: 'Fruta', translation: 'Fruit' },
            { word: 'Verdura', translation: 'Vegetable' },
            { word: 'Día', translation: 'Day' },
            { word: 'Noche', translation: 'Night' },
            { word: 'Mañana', translation: 'Morning' },
            { word: 'Tarde', translation: 'Afternoon' },
            { word: 'Tiempo', translation: 'Time' },
            { word: 'Hora', translation: 'Hour' },
            { word: 'Hoy', translation: 'Today' },
            { word: 'Ayer', translation: 'Yesterday' },
            { word: 'Mañana', translation: 'Tomorrow' },
            { word: 'Sol', translation: 'Sun' },
            { word: 'Luna', translation: 'Moon' },
            { word: 'Cielo', translation: 'Sky' },
            { word: 'Tierra', translation: 'Earth' },
            { word: 'Mar', translation: 'Sea' },
            { word: 'Fuego', translation: 'Fire' },
            { word: 'Aire', translation: 'Air' },
            { word: 'Animal', translation: 'Animal' },
            { word: 'Perro', translation: 'Dog' },
            { word: 'Gato', translation: 'Cat' },
            { word: 'Pájaro', translation: 'Bird' },
            { word: 'Pez', translation: 'Fish' },
            { word: 'Coche', translation: 'Car' },
            { word: 'Tren', translation: 'Train' },
            { word: 'Avión', translation: 'Plane' },
            { word: 'Calle', translation: 'Street' },
            { word: 'Ciudad', translation: 'City' },
            { word: 'País', translation: 'Country' },
            { word: 'Mundo', translation: 'World' },
            { word: 'Trabajo', translation: 'Work' },
            { word: 'Dinero', translation: 'Money' },
            { word: 'Teléfono', translation: 'Phone' },
            { word: 'Ordenador', translation: 'Computer' },
            { word: 'Mano', translation: 'Hand' },
            { word: 'Pie', translation: 'Foot' },
            { word: 'Cabeza', translation: 'Head' },
            { word: 'Ojo', translation: 'Eye' },
            { word: 'Boca', translation: 'Mouth' },
            { word: 'Nariz', translation: 'Nose' },
            { word: 'Oreja', translation: 'Ear' },
            { word: 'Camisa', translation: 'Shirt' },
            { word: 'Pantalón', translation: 'Pants' },
            { word: 'Zapato', translation: 'Shoe' },
            { word: 'Ropa', translation: 'Clothes' },
            { word: 'Frío', translation: 'Cold' },
            { word: 'Calor', translation: 'Hot' },
            { word: 'Feliz', translation: 'Happy' },
            { word: 'Triste', translation: 'Sad' },
            { word: 'Grande', translation: 'Big' },
            { word: 'Pequeño', translation: 'Small' },
            { word: 'Nuevo', translation: 'New' },
            { word: 'Viejo', translation: 'Old' },
            { word: 'Bueno', translation: 'Good' },
            { word: 'Malo', translation: 'Bad' },
            { word: 'Bonito', translation: 'Pretty' },
            { word: 'Feo', translation: 'Ugly' },
            { word: 'Alto', translation: 'Tall' },
            { word: 'Bajo', translation: 'Short' },
            { word: 'Rápido', translation: 'Fast' },
            { word: 'Lento', translation: 'Slow' },
            { word: 'Fuerte', translation: 'Strong' },
            { word: 'Débil', translation: 'Weak' },
            { word: 'Fácil', translation: 'Easy' },
            { word: 'Difícil', translation: 'Difficult' },
            { word: 'Aquí', translation: 'Here' },
            { word: 'Allí', translation: 'There' },
            { word: 'Arriba', translation: 'Up' },
            { word: 'Abajo', translation: 'Down' },
            { word: 'Dentro', translation: 'Inside' },
            { word: 'Fuera', translation: 'Outside' },
            { word: 'Siempre', translation: 'Always' },
            { word: 'Nunca', translation: 'Never' },
            { word: 'A veces', translation: 'Sometimes' },
            { word: 'Porque', translation: 'Because' },
            { word: 'Pero', translation: 'But' },
        ],
      },
      intermediate: {
        name: 'Intermedio (B1-B2)',
        words: [
            { word: 'Acuerdo', translation: 'Agreement' },
            { word: 'Adivinar', translation: 'Guess' },
            { word: 'Agradecer', translation: 'Appreciate' },
            { word: 'Alegría', translation: 'Joy' },
            { word: 'Alquiler', translation: 'Rent' },
            { word: 'Ambiente', translation: 'Environment' },
            { word: 'Amistad', translation: 'Friendship' },
            { word: 'Anfitrión', translation: 'Host' },
            { word: 'Apoyo', translation: 'Support' },
            { word: 'Aprovechar', translation: 'Take advantage' },
            { word: 'Aterrizar', translation: 'Land (a plane)' },
            { word: 'Aumentar', translation: 'Increase' },
            { word: 'Averiguar', translation: 'Find out' },
            { word: 'Bajo presión', translation: 'Under pressure' },
            { word: 'Barrera', translation: 'Barrier' },
            { word: 'Beneficio', translation: 'Benefit' },
            { word: 'Calidad', translation: 'Quality' },
            { word: 'Cantidad', translation: 'Quantity' },
            { word: 'Cansancio', translation: 'Tiredness' },
            { word: 'Capaz', translation: 'Capable' },
            { word: 'Carrera', translation: 'Career / Race' },
            { word: 'Cita', translation: 'Appointment / Date' },
            { word: 'Clima', translation: 'Climate' },
            { word: 'Compartir', translation: 'Share' },
            { word: 'Comportamiento', translation: 'Behavior' },
            { word: 'Comprensión', translation: 'Understanding' },
            { word: 'Confiar', translation: 'Trust' },
            { word: 'Consejo', translation: 'Advice' },
            { word: 'Consumo', translation: 'Consumption' },
            { word: 'Contaminación', translation: 'Pollution' },
            { word: 'Contrato', translation: 'Contract' },
            { word: 'Conveniente', translation: 'Convenient' },
            { word: 'Coraje', translation: 'Courage' },
            { word: 'Creatividad', translation: 'Creativity' },
            { word: 'Crecer', translation: 'Grow' },
            { word: 'Cuadro', translation: 'Painting / Frame' },
            { word: 'Cumplir', translation: 'Fulfill / Turn (age)' },
            { word: 'Curioso', translation: 'Curious' },
            { word: 'Daño', translation: 'Damage' },
            { word: 'Débil', translation: 'Weak' },
            { word: 'Desarrollar', translation: 'Develop' },
            { word: 'Descubrir', translation: 'Discover' },
            { word: 'Desempeñar', translation: 'Perform' },
            { word: 'Desventaja', translation: 'Disadvantage' },
            { word: 'Duda', translation: 'Doubt' },
            { word: 'Éxito', translation: 'Success' },
            { word: 'Experiencia', translation: 'Experience' },
            { word: 'Exigir', translation: 'Demand' },
            { word: 'Falla', translation: 'Failure / Flaw' },
            { word: 'Fijarse', translation: 'Notice' },
            { word: 'Fomentar', translation: 'Encourage' },
            { word: 'Fracaso', translation: 'Failure' },
            { word: 'Ganar', translation: 'Win / Earn' },
            { word: 'Gasto', translation: 'Expense' },
            { word: 'Herramienta', translation: 'Tool' },
            { word: 'Huir', translation: 'Flee' },
            { word: 'Imprimir', translation: 'Print' },
            { word: 'Incluir', translation: 'Include' },
            { word: 'Influencia', translation: 'Influence' },
            { word: 'Injusto', translation: 'Unfair' },
            { word: 'Inseguridad', translation: 'Insecurity' },
            { word: 'Inversión', translation: 'Investment' },
            { word: 'Justo', translation: 'Fair' },
            { word: 'Lento', translation: 'Slow' },
            { word: 'Logro', translation: 'Achievement' },
            { word: 'Mantenimiento', translation: 'Maintenance' },
            { word: 'Mejorar', translation: 'Improve' },
            { word: 'Mensaje', translation: 'Message' },
            { word: 'Metas', translation: 'Goals' },
            { word: 'Miedo', translation: 'Fear' },
            { word: 'Molestar', translation: 'Bother' },
            { word: 'Notar', translation: 'Notice' },
            { word: 'Observar', translation: 'Observe' },
            { word: 'Oportunidad', translation: 'Opportunity' },
            { word: 'Orgullo', translation: 'Pride' },
            { word: 'Parecer', translation: 'Seem' },
            { word: 'Participar', translation: 'Participate' },
            { word: 'Peligro', translation: 'Danger' },
            { word: 'Pérdida', translation: 'Loss' },
            { word: 'Persuadir', translation: 'Persuade' },
            { word: 'Plazo', translation: 'Deadline / Term' },
            { word: 'Portátil', translation: 'Laptop' },
            { word: 'Postura', translation: 'Posture / Position' },
            { word: 'Preciso', translation: 'Precise' },
            { word: 'Presión', translation: 'Pressure' },
            { word: 'Prevenir', translation: 'Prevent' },
            { word: 'Prioridad', translation: 'Priority' },
            { word: 'Propuesta', translation: 'Proposal' },
            { word: 'Queja', translation: 'Complaint' },
            { word: 'Rechazar', translation: 'Reject' },
            { word: 'Reducir', translation: 'Reduce' },
            { word: 'Refuerzo', translation: 'Reinforcement' },
            { word: 'Requisito', translation: 'Requirement' },
            { word: 'Resolver', translation: 'Solve' },
            { word: 'Riesgo', translation: 'Risk' },
            { word: 'Reto', translation: 'Challenge' },
            { word: 'Seguro', translation: 'Safe / Insurance' },
            { word: 'Sugerencia', translation: 'Suggestion' },
            { word: 'Superar', translation: 'Overcome' },
            { word: 'Valorar', translation: 'Value' },
        ],
      },
      advanced: {
        name: 'Avanzado (C1-C2)',
        words: [
            { word: 'Abrumador', translation: 'Overwhelming' },
            { word: 'Acontecimientos', translation: 'Events' },
            { word: 'Adecuado', translation: 'Suitable' },
            { word: 'Afirmación', translation: 'Statement' },
            { word: 'Agotar', translation: 'Exhaust' },
            { word: 'Alcanzar', translation: 'Achieve' },
            { word: 'Ambiguo', translation: 'Ambiguous' },
            { word: 'Análisis', translation: 'Analysis' },
            { word: 'Anhelar', translation: 'Long for' },
            { word: 'Anticipar', translation: 'Anticipate' },
            { word: 'Apoderarse', translation: 'Seize' },
            { word: 'Argumentar', translation: 'Argue' },
            { word: 'Arraigado', translation: 'Deep-rooted' },
            { word: 'Articular', translation: 'Articulate' },
            { word: 'Asertivo', translation: 'Assertive' },
            { word: 'Asimilación', translation: 'Assimilation' },
            { word: 'Asombroso', translation: 'Astonishing' },
            { word: 'Atribuir', translation: 'Attribute' },
            { word: 'Autonomía', translation: 'Autonomy' },
            { word: 'Avanzar', translation: 'Advance' },
            { word: 'Beneficioso', translation: 'Beneficial' },
            { word: 'Capacidad', translation: 'Capacity' },
            { word: 'Coherencia', translation: 'Coherence' },
            { word: 'Colaboración', translation: 'Collaboration' },
            { word: 'Compensar', translation: 'Compensate' },
            { word: 'Complejidad', translation: 'Complexity' },
            { word: 'Componente', translation: 'Component' },
            { word: 'Comprometido', translation: 'Committed' },
            { word: 'Concretar', translation: 'Specify' },
            { word: 'Confiabilidad', translation: 'Reliability' },
            { word: 'Connotación', translation: 'Connotation' },
            { word: 'Consolidar', translation: 'Consolidate' },
            { word: 'Contundente', translation: 'Forceful' },
            { word: 'Contradicción', translation: 'Contradiction' },
            { word: 'Convicción', translation: 'Conviction' },
            { word: 'Correlación', translation: 'Correlation' },
            { word: 'Cuestionar', translation: 'Question' },
            { word: 'Cualitativo', translation: 'Qualitative' },
            { word: 'Cuantitativo', translation: 'Quantitative' },
            { word: 'Deficiencia', translation: 'Deficiency' },
            { word: 'Deliberado', translation: 'Deliberate' },
            { word: 'Demostrar', translation: 'Demonstrate' },
            { word: 'Desafiar', translation: 'Challenge' },
            { word: 'Desempeño', translation: 'Performance' },
            { word: 'Desplazamiento', translation: 'Displacement' },
            { word: 'Deterioro', translation: 'Deterioration' },
            { word: 'Diferenciación', translation: 'Differentiation' },
            { word: 'Discrepancia', translation: 'Discrepancy' },
            { word: 'Disposición', translation: 'Disposition' },
            { word: 'Distinción', translation: 'Distinction' },
            { word: 'Diversidad', translation: 'Diversity' },
            { word: 'Eficacia', translation: 'Effectiveness' },
            { word: 'Eficiencia', translation: 'Efficiency' },
            { word: 'Elaborar', translation: 'Develop (in detail)' },
            { word: 'Empatía', translation: 'Empathy' },
            { word: 'Enfatizar', translation: 'Emphasize' },
            { word: 'Enriquecer', translation: 'Enrich' },
            { word: 'Equilibrio', translation: 'Balance' },
            { word: 'Esencial', translation: 'Essential' },
            { word: 'Especificar', translation: 'Specify' },
            { word: 'Estimación', translation: 'Estimation' },
            { word: 'Estrategia', translation: 'Strategy' },
            { word: 'Exponer', translation: 'Expose / Present' },
            { word: 'Facilitar', translation: 'Facilitate' },
            { word: 'Factible', translation: 'Feasible' },
            { word: 'Fundamentar', translation: 'Base (an argument)' },
            { word: 'Globalización', translation: 'Globalization' },
            { word: 'Hipótesis', translation: 'Hypothesis' },
            { word: 'Identidad', translation: 'Identity' },
            { word: 'Imparcial', translation: 'Impartial' },
            { word: 'Implicación', translation: 'Implication' },
            { word: 'Incertidumbre', translation: 'Uncertainty' },
            { word: 'Indicador', translation: 'Indicator' },
            { word: 'Inferir', translation: 'Infer' },
            { word: 'Influencia', translation: 'Influence' },
            { word: 'Iniciativa', translation: 'Initiative' },
            { word: 'Innovación', translation: 'Innovation' },
            { word: 'Integridad', translation: 'Integrity' },
            { word: 'Intervención', translation: 'Intervention' },
            { word: 'Justificación', translation: 'Justification' },
            { word: 'Lógica', translation: 'Logic' },
            { word: 'Manifestación', translation: 'Demonstration / Manifestation' },
            { word: 'Matizar', translation: 'Qualify (a statement)' },
            { word: 'Medición', translation: 'Measurement' },
            { word: 'Metodología', translation: 'Methodology' },
            { word: 'Motivación', translation: 'Motivation' },
            { word: 'Objetividad', translation: 'Objectivity' },
            { word: 'Paradigma', translation: 'Paradigm' },
            { word: 'Perspectiva', translation: 'Perspective' },
            { word: 'Plantear', translation: 'Raise (a topic)' },
            { word: 'Precisión', translation: 'Precision' },
            { word: 'Presuponer', translation: 'Presume' },
            { word: 'Proceso', translation: 'Process' },
            { word: 'Profundizar', translation: 'Deepen' },
            { word: 'Propuesta', translation: 'Proposal' },
            { word: 'Razonamiento', translation: 'Reasoning' },
            { word: 'Reconocimiento', translation: 'Recognition' },
            { word: 'Refutar', translation: 'Refute' },
            { word: 'Relevante', translation: 'Relevant' },
            { word: 'Sustentar', translation: 'Support (an argument)' },
        ],
      },
      phrasalVerbs: {
        name: 'Phrasal Verbs',
        words: [
          { word: 'Wake up', translation: 'Despertarse' },
          { word: 'Get up', translation: 'Levantarse' },
          { word: 'Turn on', translation: 'Encender' },
          { word: 'Turn off', translation: 'Apagar' },
          { word: 'Go out', translation: 'Salir' },
          { word: 'Come in', translation: 'Entrar' },
          { word: 'Sit down', translation: 'Sentarse' },
          { word: 'Stand up', translation: 'Levantarse' },
          { word: 'Give up', translation: 'Rendirse' },
          { word: 'Carry on', translation: 'Continuar' },
          { word: 'Look for', translation: 'Buscar' },
          { word: 'Look after', translation: 'Cuidar' },
          { word: 'Look up', translation: 'Buscar (en un diccionario)' },
          { word: 'Take off', translation: 'Quitarse / Despegar' },
          { word: 'Put on', translation: 'Ponerse (ropa)' },
          { word: 'Run out of', translation: 'Quedarse sin' },
          { word: 'Make up', translation: 'Inventar / Reconciliarse' },
          { word: 'Break down', translation: 'Averiarse / Derrumbarse' },
          { word: 'Bring up', translation: 'Mencionar / Criar' },
          { word: 'Calm down', translation: 'Calmarse' },
          { word: 'Call off', translation: 'Cancelar' },
          { word: 'Check in', translation: 'Registrarse' },
          { word: 'Check out', translation: 'Salir (hotel) / Revisar' },
          { word: 'Come back', translation: 'Volver' },
          { word: 'Come up with', translation: 'Inventar / Proponer' },
          { word: 'Cut down on', translation: 'Reducir' },
          { word: 'Do over', translation: 'Repetir' },
          { word: 'Drop off', translation: 'Dejar (a alguien)' },
          { word: 'Figure out', translation: 'Resolver / Entender' },
          { word: 'Fill in', translation: 'Rellenar (formulario)' },
          { word: 'Find out', translation: 'Descubrir' },
          { word: 'Get along', translation: 'Llevarse bien' },
          { word: 'Get by', translation: 'Arreglárselas' },
          { word: 'Get in', translation: 'Entrar' },
          { word: 'Get off', translation: 'Bajarse' },
          { word: 'Get on', translation: 'Subirse' },
          { word: 'Get over', translation: 'Superar' },
          { word: 'Give away', translation: 'Regalar' },
          { word: 'Go away', translation: 'Irse' },
          { word: 'Go back', translation: 'Volver' },
          { word: 'Go on', translation: 'Continuar' },
          { word: 'Grow up', translation: 'Crecer' },
          { word: 'Hang out', translation: 'Pasar el rato' },
          { word: 'Hold on', translation: 'Esperar' },
          { word: 'Keep on', translation: 'Seguir' },
          { word: 'Let down', translation: 'Decepcionar' },
          { word: 'Look out', translation: 'Cuidado / Estar atento' },
          { word: 'Move on', translation: 'Avanzar' },
          { word: 'Pass away', translation: 'Fallecer' },
        ]
      }
    };