export const professionalLists = {
      technology: {
        name: 'Tecnología',
        words: [
            { word: 'Ordenador', translation: 'Computer' },
            { word: 'Internet', translation: 'Internet' },
            { word: 'Red', translation: 'Network' },
            { word: 'Datos', translation: 'Data' },
            { word: 'Software', translation: 'Software' },
            { word: 'Hardware', translation: 'Hardware' },
            { word: 'Aplicación', translation: 'Application' },
            { word: 'Dispositivo', translation: 'Device' },
            { word: 'Pantalla', translation: 'Screen' },
            { word: 'Teclado', translation: 'Keyboard' },
            { word: 'Ratón', translation: 'Mouse' },
            { word: 'Móvil', translation: 'Mobile' },
            { word: 'Inteligencia artificial', translation: 'Artificial intelligence' },
            { word: 'Algoritmo', translation: 'Algorithm' },
            { word: 'Código', translation: 'Code' },
            { word: 'Programación', translation: 'Programming' },
            { word: 'Sistema operativo', translation: 'Operating system' },
            { word: 'Archivo', translation: 'File' },
            { word: 'Carpeta', translation: 'Folder' },
            { word: 'Ciberseguridad', translation: 'Cybersecurity' },
            { word: 'Robot', translation: 'Robot' },
            { word: 'Red social', translation: 'Social network' },
            { word: 'Base de datos', translation: 'Database' },
            { word: 'Servidor', translation: 'Server' },
            { word: 'Nube', translation: 'Cloud' },
            { word: 'Actualización', translation: 'Update' },
            { word: 'Descarga', translation: 'Download' },
            { word: 'Subida', translation: 'Upload' },
            { word: 'Enlace', translation: 'Link' },
            { word: 'Navegador', translation: 'Browser' },
            { word: 'Página web', translation: 'Website' },
            { word: 'Usuario', translation: 'User' },
            { word: 'Contraseña', translation: 'Password' },
            { word: 'Pantalla táctil', translation: 'Touchscreen' },
            { word: 'Procesador', translation: 'Processor' },
            { word: 'Memoria', translation: 'Memory' },
            { word: 'Almacenamiento', translation: 'Storage' },
            { word: 'Inteligente', translation: 'Smart' },
            { word: 'Conexión', translation: 'Connection' },
            { word: 'Virus', translation: 'Virus' },
            { word: 'Malware', translation: 'Malware' },
            { word: 'Red inalámbrica', translation: 'Wireless network' },
            { word: 'Bluetooth', translation: 'Bluetooth' },
            { word: 'Sensor', translation: 'Sensor' },
            { word: 'Tecnología', translation: 'Technology' },
            { word: 'Electrónica', translation: 'Electronics' },
            { word: 'Streaming', translation: 'Streaming' },
            { word: 'Resolución', translation: 'Resolution' },
            { word: 'Imagen', translation: 'Image' },
            { word: 'Vídeo', translation: 'Video' },
            { word: 'Audio', translation: 'Audio' },
            { word: 'Inteligencia', translation: 'Intelligence' },
            { word: 'Integración', translation: 'Integration' },
            { word: 'Automatización', translation: 'Automation' },
            { word: 'Consola', translation: 'Console' },
            { word: 'Videojuego', translation: 'Videogame' },
            { word: 'Plataforma', translation: 'Platform' },
            { word: 'Configuración', translation: 'Configuration' },
            { word: 'Usuario final', translation: 'End user' },
            { word: 'Dominio', translation: 'Domain' },
            { word: 'Hosting', translation: 'Hosting' },
            { word: 'Interfaz', translation: 'Interface' },
            { word: 'Red virtual', translation: 'Virtual network' },
            { word: 'Seguridad', translation: 'Security' },
            { word: 'Firewal', translation: 'Firewall' },
            { word: 'IP', translation: 'IP' },
            { word: 'Router', translation: 'Router' },
            { word: 'Cable', translation: 'Cable' },
            { word: 'HDMI', translation: 'HDMI' },
            { word: 'USB', translation: 'USB' },
            { word: 'Fuente de energía', translation: 'Power supply' },
            { word: 'Batería', translation: 'Battery' },
            { word: 'Portátil', translation: 'Laptop' },
            { word: 'Escritorio', translation: 'Desktop' },
            { word: 'Tablet', translation: 'Tablet' },
            { word: 'Altavoz', translation: 'Speaker' },
            { word: 'Micrófono', translation: 'Microphone' },
            { word: 'Cámara', translation: 'Camera' },
            { word: 'Simulación', translation: 'Simulation' },
            { word: 'Realidad virtual', translation: 'Virtual reality' },
            { word: 'Realidad aumentada', translation: 'Augmented reality' },
            { word: 'Inteligencia computacional', translation: 'Computational intelligence' },
            { word: 'Big Data', translation: 'Big Data' },
            { word: 'Análisis', translation: 'Analytics' },
            { word: 'Criptografía', translation: 'Cryptography' },
            { word: 'Blockchain', translation: 'Blockchain' },
            { word: 'Token', translation: 'Token' },
            { word: 'Código abierto', translation: 'Open source' },
            { word: 'Licencia', translation: 'License' },
            { word: 'Desarrollador', translation: 'Developer' },
            { word: 'Interfaz gráfica', translation: 'Graphical interface' },
            { word: 'Chatbot', translation: 'Chatbot' },
            { word: 'Navegación', translation: 'Navigation' },
            { word: 'Tarea automática', translation: 'Automated task' },
            { word: 'Red neuronal', translation: 'Neural network' },
            { word: 'Machine learning', translation: 'Machine learning' },
            { word: 'Entrenamiento', translation: 'Training' },
            { word: 'Datos de entrada', translation: 'Input data' },
            { word: 'Datos de salida', translation: 'Output data' },
            { word: 'Digitalización', translation: 'Digitization' },
        ],
      },
      health: {
        name: 'Sanidad',
        words: [
            { word: 'Salud', translation: 'Health' },
            { word: 'Enfermedad', translation: 'Illness' },
            { word: 'Médico', translation: 'Doctor' },
            { word: 'Paciente', translation: 'Patient' },
            { word: 'Hospital', translation: 'Hospital' },
            { word: 'Clínica', translation: 'Clinic' },
            { word: 'Ambulancia', translation: 'Ambulance' },
            { word: 'Medicamento', translation: 'Medicine' },
            { word: 'Pastilla', translation: 'Pill' },
            { word: 'Jarabe', translation: 'Syrup' },
            { word: 'Inyección', translation: 'Injection' },
            { word: 'Termómetro', translation: 'Thermometer' },
            { word: 'Estetoscopio', translation: 'Stethoscope' },
            { word: 'Presión arterial', translation: 'Blood pressure' },
            { word: 'Pulso', translation: 'Pulse' },
            { word: 'Ritmo cardíaco', translation: 'Heart rate' },
            { word: 'Sangre', translation: 'Blood' },
            { word: 'Análisis', translation: 'Analysis' },
            { word: 'Diagnóstico', translation: 'Diagnosis' },
            { word: 'Tratamiento', translation: 'Treatment' },
            { word: 'Cirugía', translation: 'Surgery' },
            { word: 'Operación', translation: 'Operation' },
            { word: 'Herida', translation: 'Wound' },
            { word: 'Fractura', translation: 'Fracture' },
            { word: 'Fiebre', translation: 'Fever' },
            { word: 'Dolor', translation: 'Pain' },
            { word: 'Dolor de cabeza', translation: 'Headache' },
            { word: 'Dolor de garganta', translation: 'Sore throat' },
            { word: 'Dolor de estómago', translation: 'Stomachache' },
            { word: 'Gripe', translation: 'Flu' },
            { word: 'Resfriado', translation: 'Cold' },
            { word: 'Tos', translation: 'Cough' },
            { word: 'Náuseas', translation: 'Nausea' },
            { word: 'Vómito', translation: 'Vomit' },
            { word: 'Mareo', translation: 'Dizziness' },
            { word: 'Cansancio', translation: 'Tiredness' },
            { word: 'Estrés', translation: 'Stress' },
            { word: 'Ansiedad', translation: 'Anxiety' },
            { word: 'Depresión', translation: 'Depression' },
            { word: 'Vacuna', translation: 'Vaccine' },
            { word: 'Revisión médica', translation: 'Medical check-up' },
            { word: 'Urgencias', translation: 'Emergency' },
            { word: 'Enfermero', translation: 'Nurse' },
            { word: 'Cita médica', translation: 'Medical appointment' },
            { word: 'Seguro médico', translation: 'Health insurance' },
            { word: 'Rehabilitación', translation: 'Rehabilitation' },
            { word: 'Higiene', translation: 'Hygiene' },
            { word: 'Nutrición', translation: 'Nutrition' },
            { word: 'Ejercicio', translation: 'Exercise' },
            { word: 'Bienestar', translation: 'Well-being' },
        ],
      },
      education: {
        name: 'Educación',
        words: [
            { word: 'Escuela', translation: 'School' },
            { word: 'Universidad', translation: 'University' },
            { word: 'Instituto', translation: 'High school' },
            { word: 'Aula', translation: 'Classroom' },
            { word: 'Estudiante', translation: 'Student' },
            { word: 'Profesor', translation: 'Teacher' },
            { word: 'Clase', translation: 'Class' },
            { word: 'Curso', translation: 'Course' },
            { word: 'Tarea', translation: 'Homework' },
            { word: 'Examen', translation: 'Exam' },
            { word: 'Nota', translation: 'Grade' },
            { word: 'Aprendizaje', translation: 'Learning' },
            { word: 'Enseñanza', translation: 'Teaching' },
            { word: 'Lección', translation: 'Lesson' },
            { word: 'Evaluación', translation: 'Assessment' },
            { word: 'Libro', translation: 'Book' },
            { word: 'Cuaderno', translation: 'Notebook' },
            { word: 'Bolígrafo', translation: 'Pen' },
            { word: 'Lápiz', translation: 'Pencil' },
            { word: 'Mochila', translation: 'Backpack' },
            { word: 'Escritorio', translation: 'Desk' },
            { word: 'Pizarra', translation: 'Blackboard' },
            { word: 'Silla', translation: 'Chair' },
            { word: 'Idioma', translation: 'Language' },
            { word: 'Matemáticas', translation: 'Math' },
            { word: 'Ciencia', translation: 'Science' },
            { word: 'Historia', translation: 'History' },
            { word: 'Geografía', translation: 'Geography' },
            { word: 'Lectura', translation: 'Reading' },
            { word: 'Escritura', translation: 'Writing' },
            { word: 'Tutoría', translation: 'Tutoring' },
            { word: 'Tutor', translation: 'Tutor' },
            { word: 'Alumno', translation: 'Pupil' },
            { word: 'Compañero', translation: 'Classmate' },
            { word: 'Asistencia', translation: 'Attendance' },
            { word: 'Biblioteca', translation: 'Library' },
            { word: 'Investigación', translation: 'Research' },
            { word: 'Beca', translation: 'Scholarship' },
            { word: 'Diploma', translation: 'Diploma' },
            { word: 'Grado', translation: 'Degree' },
            { word: 'Licenciatura', translation: 'Bachelor\'s degree' },
            { word: 'Máster', translation: 'Master\'s degree' },
            { word: 'Doctorado', translation: 'PhD' },
            { word: 'Plan de estudios', translation: 'Curriculum' },
            { word: 'Horario', translation: 'Schedule' },
            { word: 'Receso', translation: 'Break' },
            { word: 'Recreo', translation: 'Recess' },
            { word: 'Uniforme', translation: 'Uniform' },
            { word: 'Aula virtual', translation: 'Virtual classroom' },
            { word: 'Educación online', translation: 'Online education' },
            { word: 'Videollamada', translation: 'Video call' },
            { word: 'Plataforma', translation: 'Platform' },
            { word: 'Asignatura', translation: 'Subject' },
            { word: 'Exposición', translation: 'Presentation' },
            { word: 'Debate', translation: 'Debate' },
            { word: 'Redacción', translation: 'Essay' },
            { word: 'Creatividad', translation: 'Creativity' },
            { word: 'Pensamiento crítico', translation: 'Critical thinking' },
            { word: 'Motivación', translation: 'Motivation' },
            { word: 'Conocimiento', translation: 'Knowledge' },
            { word: 'Comprensión', translation: 'Understanding' },
            { word: 'Participación', translation: 'Participation' },
            { word: 'Evaluador', translation: 'Examiner' },
            { word: 'Examinado', translation: 'Examinee' },
            { word: 'Resultado', translation: 'Result' },
            { word: 'Boletín', translation: 'Report card' },
            { word: 'Escuela pública', translation: 'Public school' },
            { word: 'Escuela privada', translation: 'Private school' },
            { word: 'Aula de informática', translation: 'Computer lab' },
            { word: 'Aula de ciencias', translation: 'Science lab' },
            { word: 'Gimnasio', translation: 'Gymnasium' },
            { word: 'Laboratorio', translation: 'Laboratory' },
            { word: 'Actividades extracurriculares', translation: 'Extracurricular activities' },
            { word: 'Manual', translation: 'Manual' },
            { word: 'Apuntes', translation: 'Notes' },
            { word: 'Asignación', translation: 'Assignment' },
            { word: 'Evaluación continua', translation: 'Continuous assessment' },
            { word: 'Rúbrica', translation: 'Rubric' },
            { word: 'Profesorado', translation: 'Faculty' },
            { word: 'Director', translation: 'Principal' },
            { word: 'Coordinador', translation: 'Coordinator' },
            { word: 'Ayudante', translation: 'Assistant' },
            { word: 'Orientador', translation: 'Counselor' },
            { word: 'Psicopedagogo', translation: 'Educational psychologist' },
            { word: 'Educación infantil', translation: 'Early education' },
            { word: 'Primaria', translation: 'Primary school' },
            { word: 'Secundaria', translation: 'Secondary school' },
            { word: 'Educación superior', translation: 'Higher education' },
            { word: 'Formación profesional', translation: 'Vocational training' },
            { word: 'Escuela técnica', translation: 'Technical school' },
            { word: 'Conferencia', translation: 'Lecture' },
            { word: 'Seminario', translation: 'Seminar' },
            { word: 'Taller', translation: 'Workshop' },
            { word: 'Inscripción', translation: 'Enrollment' },
            { word: 'Registro', translation: 'Registration' },
            { word: 'Matriculación', translation: 'Enrollment' },
            { word: 'Exposición oral', translation: 'Oral presentation' },
            { word: 'Normas escolares', translation: 'School rules' },
            { word: 'Calendario escolar', translation: 'School calendar' },
            { word: 'Aula invertida', translation: 'Flipped classroom' },
        ],
      },
      business: {
        name: 'Negocios',
        words: [
          { word: 'Empresa', translation: 'Company' },
          { word: 'Negocio', translation: 'Business' },
          { word: 'Emprendedor', translation: 'Entrepreneur' },
          { word: 'Inversión', translation: 'Investment' },
          { word: 'Capital', translation: 'Capital' },
          { word: 'Ganancia', translation: 'Profit' },
          { word: 'Pérdida', translation: 'Loss' },
          { word: 'Dinero', translation: 'Money' },
          { word: 'Cliente', translation: 'Client' },
          { word: 'Producto', translation: 'Product' },
          { word: 'Servicio', translation: 'Service' },
          { word: 'Factura', translation: 'Invoice' },
          { word: 'Contrato', translation: 'Contract' },
          { word: 'Presupuesto', translation: 'Budget' },
          { word: 'Venta', translation: 'Sale' },
          { word: 'Compra', translation: 'Purchase' },
          { word: 'Marketing', translation: 'Marketing' },
          { word: 'Publicidad', translation: 'Advertising' },
          { word: 'Marca', translation: 'Brand' },
          { word: 'Campaña', translation: 'Campaign' },
          { word: 'Oferta', translation: 'Offer' },
          { word: 'Demanda', translation: 'Demand' },
          { word: 'Precio', translation: 'Price' },
          { word: 'Estrategia', translation: 'Strategy' },
          { word: 'Reunión', translation: 'Meeting' },
          { word: 'Plan de negocios', translation: 'Business plan' },
          { word: 'Liderazgo', translation: 'Leadership' },
          { word: 'Gestión', translation: 'Management' },
          { word: 'Proyecto', translation: 'Project' },
          { word: 'Objetivo', translation: 'Goal' },
          { word: 'Éxito', translation: 'Success' },
          { word: 'Fracaso', translation: 'Failure' },
          { word: 'Impuesto', translation: 'Tax' },
          { word: 'Financiero', translation: 'Financial' },
          { word: 'Contabilidad', translation: 'Accounting' },
          { word: 'Salario', translation: 'Salary' },
          { word: 'Nómina', translation: 'Payroll' },
          { word: 'Capital humano', translation: 'Human capital' },
          { word: 'Recursos humanos', translation: 'Human resources' },
          { word: 'Departamento', translation: 'Department' },
          { word: 'Jefe', translation: 'Boss' },
          { word: 'Empleado', translation: 'Employee' },
          { word: 'Socio', translation: 'Partner' },
          { word: 'Ingresos', translation: 'Income' },
          { word: 'Costos', translation: 'Costs' },
          { word: 'Gastos', translation: 'Expenses' },
          { word: 'Balance', translation: 'Balance' },
          { word: 'Rentabilidad', translation: 'Profitability' },
          { word: 'Participación', translation: 'Stake' },
          { word: 'Acciones', translation: 'Shares' },
          { word: 'Bolsa', translation: 'Stock market' },
          { word: 'Dividendo', translation: 'Dividend' },
          { word: 'Riesgo', translation: 'Risk' },
          { word: 'Evaluación', translation: 'Evaluation' },
          { word: 'Cliente potencial', translation: 'Prospect' },
          { word: 'Base de clientes', translation: 'Client base' },
          { word: 'Cartera', translation: 'Portfolio' },
          { word: 'Inventario', translation: 'Inventory' },
          { word: 'Logística', translation: 'Logistics' },
          { word: 'Distribución', translation: 'Distribution' },
          { word: 'Almacén', translation: 'Warehouse' },
          { word: 'Cadena de suministro', translation: 'Supply chain' },
          { word: 'Proveedor', translation: 'Supplier' },
          { word: 'Comercio', translation: 'Trade' },
          { word: 'Competencia', translation: 'Competition' },
          { word: 'Mercado', translation: 'Market' },
          { word: 'Expansión', translation: 'Expansion' },
          { word: 'Exportación', translation: 'Export' },
          { word: 'Importación', translation: 'Import' },
          { word: 'Franquicia', translation: 'Franchise' },
          { word: 'Sucursal', translation: 'Branch' },
          { word: 'Oficina', translation: 'Office' },
          { word: 'Ventaja', translation: 'Advantage' },
          { word: 'Negociación', translation: 'Negotiation' },
          { word: 'Propuesta', translation: 'Proposal' },
          { word: 'Oferta comercial', translation: 'Business offer' },
          { word: 'Análisis', translation: 'Analysis' },
          { word: 'Benchmark', translation: 'Benchmark' },
          { word: 'Tasa de crecimiento', translation: 'Growth rate' },
          { word: 'Planificación', translation: 'Planning' },
          { word: 'Evaluador', translation: 'Appraiser' },
          { word: 'Auditoría', translation: 'Audit' },
          { word: 'Facturación', translation: 'Billing' },
          { word: 'Tesorería', translation: 'Treasury' },
          { word: 'Caja', translation: 'Cash' },
          { word: 'Préstamo', translation: 'Loan' },
          { word: 'Interés', translation: 'Interest' },
          { word: 'Crédito', translation: 'Credit' },
          { word: 'Banco', translation: 'Bank' },
          { word: 'Capital de trabajo', translation: 'Working capital' },
          { word: 'Consultoría', translation: 'Consulting' },
          { word: 'Asesor', translation: 'Advisor' },
          { word: 'Desarrollo', translation: 'Development' },
          { word: 'Innovación', translation: 'Innovation' },
          { word: 'Transformación digital', translation: 'Digital transformation' },
          { word: 'Start-up', translation: 'Start-up' },
          { word: 'Escalabilidad', translation: 'Scalability' },
          { word: 'KPI', translation: 'KPI' },
          { word: 'CRM', translation: 'CRM' },
          { word: 'Networking', translation: 'Networking' },
        ],
      },
    };