export const situationLists = {
      travel: {
        name: 'Viajes',
        words: [
            { word: 'Viaje', translation: 'Trip' },
            { word: 'Vacaciones', translation: 'Vacation' },
            { word: 'Turista', translation: 'Tourist' },
            { word: 'Turismo', translation: 'Tourism' },
            { word: 'Pasaporte', translation: 'Passport' },
            { word: 'Documento', translation: 'Document' },
            { word: 'Visa', translation: 'Visa' },
            { word: 'Destino', translation: 'Destination' },
            { word: 'Salida', translation: 'Departure' },
            { word: 'Llegada', translation: 'Arrival' },
            { word: 'Aeropuerto', translation: 'Airport' },
            { word: 'Vuelo', translation: 'Flight' },
            { word: 'Billete / Boleto', translation: 'Ticket' },
            { word: 'Reserva', translation: 'Reservation' },
            { word: 'Asiento', translation: 'Seat' },
            { word: 'Facturación', translation: 'Check-in' },
            { word: 'Equipaje', translation: 'Luggage' },
            { word: 'Maleta', translation: 'Suitcase' },
            { word: 'Mochila', translation: 'Backpack' },
            { word: 'Aduana', translation: 'Customs' },
            { word: 'Control de seguridad', translation: 'Security check' },
            { word: 'Tarjeta de embarque', translation: 'Boarding pass' },
            { word: 'Ventanilla', translation: 'Window seat' },
            { word: 'Pasillo', translation: 'Aisle' },
            { word: 'Piloto', translation: 'Pilot' },
            { word: 'Azafata', translation: 'Flight attendant' },
            { word: 'Tren', translation: 'Train' },
            { word: 'Estación', translation: 'Station' },
            { word: 'Andén', translation: 'Platform' },
            { word: 'Autobús', translation: 'Bus' },
            { word: 'Parada', translation: 'Stop' },
            { word: 'Taxi', translation: 'Taxi' },
            { word: 'Alquiler', translation: 'Rental' },
            { word: 'Coche', translation: 'Car' },
            { word: 'Conductor', translation: 'Driver' },
            { word: 'Gasolina', translation: 'Gasoline' },
            { word: 'Navegador', translation: 'GPS / Navigator' },
            { word: 'Crucero', translation: 'Cruise' },
            { word: 'Barco', translation: 'Boat' },
            { word: 'Puerto', translation: 'Port' },
            { word: 'Mapa', translation: 'Map' },
            { word: 'Guía', translation: 'Guide' },
            { word: 'Excursión', translation: 'Excursion' },
            { word: 'Tour', translation: 'Tour' },
            { word: 'Itinerario', translation: 'Itinerary' },
            { word: 'Hotel', translation: 'Hotel' },
            { word: 'Hostal', translation: 'Hostel' },
            { word: 'Alojamiento', translation: 'Accommodation' },
            { word: 'Recepción', translation: 'Reception' },
            { word: 'Habitación', translation: 'Room' },
        ],
      },
      restaurant: {
        name: 'Restaurante',
        words: [
            { word: 'Restaurante', translation: 'Restaurant' },
            { word: 'Mesa', translation: 'Table' },
            { word: 'Silla', translation: 'Chair' },
            { word: 'Menú', translation: 'Menu' },
            { word: 'Carta', translation: 'Menu (list of dishes)' },
            { word: 'Plato', translation: 'Dish / Plate' },
            { word: 'Tenedor', translation: 'Fork' },
            { word: 'Cuchillo', translation: 'Knife' },
            { word: 'Cuchara', translation: 'Spoon' },
            { word: 'Servilleta', translation: 'Napkin' },
            { word: 'Vaso', translation: 'Glass' },
            { word: 'Copa', translation: 'Wine glass' },
            { word: 'Taza', translation: 'Cup' },
            { word: 'Camarero', translation: 'Waiter' },
            { word: 'Camarera', translation: 'Waitress' },
            { word: 'Cliente', translation: 'Customer' },
            { word: 'Cuenta', translation: 'Bill / Check' },
            { word: 'Propina', translation: 'Tip' },
            { word: 'Reservar', translation: 'Book / Reserve' },
            { word: 'Reserva', translation: 'Reservation' },
            { word: 'Pedir', translation: 'Order' },
            { word: 'Servir', translation: 'Serve' },
            { word: 'Comer', translation: 'Eat' },
            { word: 'Beber', translation: 'Drink' },
            { word: 'Entrante', translation: 'Starter / Appetizer' },
            { word: 'Primer plato', translation: 'First course' },
            { word: 'Segundo plato', translation: 'Main course' },
            { word: 'Postre', translation: 'Dessert' },
            { word: 'Bebida', translation: 'Drink' },
            { word: 'Agua', translation: 'Water' },
            { word: 'Vino', translation: 'Wine' },
            { word: 'Cerveza', translation: 'Beer' },
            { word: 'Refresco', translation: 'Soft drink' },
            { word: 'Pan', translation: 'Bread' },
            { word: 'Ensalada', translation: 'Salad' },
            { word: 'Carne', translation: 'Meat' },
            { word: 'Pescado', translation: 'Fish' },
            { word: 'Pollo', translation: 'Chicken' },
            { word: 'Sopa', translation: 'Soup' },
            { word: 'Arroz', translation: 'Rice' },
            { word: 'Pasta', translation: 'Pasta' },
            { word: 'Verdura', translation: 'Vegetable' },
            { word: 'Fruta', translation: 'Fruit' },
            { word: 'Helado', translation: 'Ice cream' },
            { word: 'Azúcar', translation: 'Sugar' },
            { word: 'Sal', translation: 'Salt' },
            { word: 'Pimienta', translation: 'Pepper' },
            { word: 'Aceite', translation: 'Oil' },
            { word: 'Vinagre', translation: 'Vinegar' },
            { word: 'Delicioso', translation: 'Delicious' },
        ],
      },
      hotel: {
        name: 'Hotel',
        words: [
            { word: 'Hotel', translation: 'Hotel' },
            { word: 'Recepción', translation: 'Reception' },
            { word: 'Reservar', translation: 'Book' },
            { word: 'Habitación', translation: 'Room' },
            { word: 'Llave', translation: 'Key' },
            { word: 'Despertador', translation: 'Alarm clock' },
            { word: 'Desayuno', translation: 'Breakfast' },
            { word: 'Almuerzo', translation: 'Lunch' },
            { word: 'Cena', translation: 'Dinner' },
            { word: 'Cama', translation: 'Bed' },
            { word: 'Colchón', translation: 'Mattress' },
            { word: 'Sábana', translation: 'Sheet' },
            { word: 'Manta', translation: 'Blanket' },
            { word: 'Almohada', translation: 'Pillow' },
            { word: 'Baño', translation: 'Bathroom' },
            { word: 'Ducha', translation: 'Shower' },
            { word: 'Toalla', translation: 'Towel' },
            { word: 'Papel higiénico', translation: 'Toilet paper' },
            { word: 'Aire acondicionado', translation: 'Air conditioning' },
            { word: 'Calefacción', translation: 'Heating' },
            { word: 'Televisión', translation: 'Television' },
            { word: 'Wi-Fi', translation: 'Wi-Fi' },
            { word: 'Conexión', translation: 'Connection' },
            { word: 'Piscina', translation: 'Pool' },
            { word: 'Gimnasio', translation: 'Gym' },
            { word: 'Restaurante', translation: 'Restaurant' },
            { word: 'Bar', translation: 'Bar' },
            { word: 'Servicio de habitaciones', translation: 'Room service' },
            { word: 'Limpieza', translation: 'Cleaning' },
            { word: 'Lavandería', translation: 'Laundry' },
            { word: 'Ascensor', translation: 'Elevator' },
            { word: 'Escalera', translation: 'Stairs' },
            { word: 'Factura', translation: 'Bill' },
            { word: 'Tarjeta de crédito', translation: 'Credit card' },
            { word: 'Caja fuerte', translation: 'Safe' },
            { word: 'Maleta', translation: 'Suitcase' },
            { word: 'Equipaje', translation: 'Luggage' },
            { word: 'Check-in', translation: 'Check-in' },
            { word: 'Check-out', translation: 'Check-out' },
            { word: 'Recepcionista', translation: 'Receptionist' },
            { word: 'Cliente', translation: 'Guest' },
            { word: 'Reserva', translation: 'Reservation' },
            { word: 'Cancelación', translation: 'Cancellation' },
            { word: 'Disponible', translation: 'Available' },
            { word: 'Ocupado', translation: 'Occupied' },
            { word: 'Vista al mar', translation: 'Sea view' },
            { word: 'Balcón', translation: 'Balcony' },
            { word: 'Planta baja', translation: 'Ground floor' },
            { word: 'Planta alta', translation: 'Upper floor' },
            { word: 'Horario', translation: 'Schedule' },
        ],
      },
      shopping: {
        name: 'Compras',
        words: [
            { word: 'Tienda', translation: 'Store' },
            { word: 'Supermercado', translation: 'Supermarket' },
            { word: 'Centro comercial', translation: 'Mall' },
            { word: 'Mercado', translation: 'Market' },
            { word: 'Dinero', translation: 'Money' },
            { word: 'Precio', translation: 'Price' },
            { word: 'Descuento', translation: 'Discount' },
            { word: 'Oferta', translation: 'Offer' },
            { word: 'Carrito', translation: 'Cart' },
            { word: 'Caja', translation: 'Checkout' },
            { word: 'Cajero', translation: 'Cashier' },
            { word: 'Tarjeta', translation: 'Card' },
            { word: 'Efectivo', translation: 'Cash' },
            { word: 'Billete', translation: 'Bill (banknote)' },
            { word: 'Moneda', translation: 'Coin' },
            { word: 'Recibo', translation: 'Receipt' },
            { word: 'Devolución', translation: 'Return' },
            { word: 'Cambio', translation: 'Change' },
            { word: 'Producto', translation: 'Product' },
            { word: 'Artículo', translation: 'Item' },
            { word: 'Cliente', translation: 'Customer' },
            { word: 'Dependiente', translation: 'Shop assistant' },
            { word: 'Talla', translation: 'Size' },
            { word: 'Color', translation: 'Color' },
            { word: 'Estilo', translation: 'Style' },
            { word: 'Marca', translation: 'Brand' },
            { word: 'Ropa', translation: 'Clothes' },
            { word: 'Zapatos', translation: 'Shoes' },
            { word: 'Camiseta', translation: 'T-shirt' },
            { word: 'Pantalones', translation: 'Pants' },
            { word: 'Abrigo', translation: 'Coat' },
            { word: 'Bufanda', translation: 'Scarf' },
            { word: 'Gafas de sol', translation: 'Sunglasses' },
            { word: 'Juguete', translation: 'Toy' },
            { word: 'Electrónica', translation: 'Electronics' },
            { word: 'Teléfono móvil', translation: 'Mobile phone' },
            { word: 'Ordenador', translation: 'Computer' },
            { word: 'Comida', translation: 'Food' },
            { word: 'Bebida', translation: 'Drink' },
            { word: 'Botella', translation: 'Bottle' },
            { word: 'Bolsa', translation: 'Bag' },
            { word: 'Caro', translation: 'Expensive' },
            { word: 'Barato', translation: 'Cheap' },
            { word: 'Probarse', translation: 'Try on' },
            { word: 'Comprar', translation: 'Buy' },
            { word: 'Vender', translation: 'Sell' },
            { word: 'Elegir', translation: 'Choose' },
            { word: 'Buscar', translation: 'Search' },
            { word: 'Encontrar', translation: 'Find' },
            { word: 'Abrir', translation: 'Open' },
            { word: 'Cerrar', translation: 'Close' },
        ],
      },
      emergencies: {
        name: 'Emergencias',
        words: [
            { word: 'Emergencia', translation: 'Emergency' },
            { word: 'Ayuda', translation: 'Help' },
            { word: 'Policía', translation: 'Police' },
            { word: 'Ambulancia', translation: 'Ambulance' },
            { word: 'Bomberos', translation: 'Firefighters' },
            { word: 'Hospital', translation: 'Hospital' },
            { word: 'Médico', translation: 'Doctor' },
            { word: 'Enfermera', translation: 'Nurse' },
            { word: 'Herida', translation: 'Wound' },
            { word: 'Sangre', translation: 'Blood' },
            { word: 'Accidente', translation: 'Accident' },
            { word: 'Urgente', translation: 'Urgent' },
            { word: 'Llamar', translation: 'Call' },
            { word: 'Teléfono', translation: 'Phone' },
            { word: 'Dirección', translation: 'Address' },
            { word: 'Dolor', translation: 'Pain' },
            { word: 'Dolor de cabeza', translation: 'Headache' },
            { word: 'Fiebre', translation: 'Fever' },
            { word: 'Náuseas', translation: 'Nausea' },
            { word: 'Mareo', translation: 'Dizziness' },
            { word: 'Desmayo', translation: 'Faint' },
            { word: 'Pérdida', translation: 'Loss' },
            { word: 'Robo', translation: 'Theft' },
            { word: 'Asalto', translation: 'Assault' },
            { word: 'Pasaporte', translation: 'Passport' },
            { word: 'Documento', translation: 'Document' },
            { word: 'Seguro médico', translation: 'Medical insurance' },
            { word: 'Alergia', translation: 'Allergy' },
            { word: 'Infección', translation: 'Infection' },
            { word: 'Veneno', translation: 'Poison' },
            { word: 'Quemadura', translation: 'Burn' },
            { word: 'Cortadura', translation: 'Cut' },
            { word: 'Fractura', translation: 'Fracture' },
            { word: 'Medicamento', translation: 'Medicine' },
            { word: 'Farmacia', translation: 'Pharmacy' },
            { word: 'Oxígeno', translation: 'Oxygen' },
            { word: 'Reanimación', translation: 'Resuscitation' },
            { word: 'Intoxicación', translation: 'Intoxication' },
            { word: 'Grito', translation: 'Scream' },
            { word: 'Ladrón', translation: 'Thief' },
            { word: 'Peligro', translation: 'Danger' },
            { word: 'Salida de emergencia', translation: 'Emergency exit' },
            { word: 'Sirena', translation: 'Siren' },
            { word: 'Botiquín', translation: 'First-aid kit' },
            { word: 'Policía local', translation: 'Local police' },
            { word: 'Centro de salud', translation: 'Health center' },
            { word: 'Urgencias', translation: 'Emergency room' },
            { word: 'Respira', translation: 'Breathe' },
            { word: 'Quema', translation: 'Burn (noun/verb)' },
            { word: 'Golpe', translation: 'Hit / blow' },
        ],
      },
    };